[package]
name = "mm"
version = "0.1.0"
authors = ["Georgy Firsov <gfirsov007@gmail.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/GeorgyFirsov/mm"
license-file = "LICENSE"

[dependencies]
git2 = "0.15"
clap = "4.0.32"
dirs = "4.0.0"
